# yamllint configuration for Home Assistant blueprints
extends: relaxed

rules:
  line-length:
    max: 120
    level: warning

  indentation:
    spaces: 2

  comments:
    min-spaces-from-content: 1

  document-start:
    present: false

  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false

  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
