blueprint:
  name: Volets - Scenes par paliers de temperature + filtre Soleil + retour avant coucher (+ actions T1/T2/T3 + hysteresis + garde T3 + zone state)
  description: >
    Scenes T1/T2 avec hysteresis (H1/H2) et filtre Soleil. T3 (ouverture) uniquement si T1/T2
    a deja ete applique (garde T3). 5 min avant le coucher du soleil: restore snapshot et reset zone.
    Les actions T1/T2 ne s executent qu une seule fois par entree de zone (input_select none/t1/t2).
  domain: automation

  input:
    temp_sensor:
      name: Capteur de temperature
      description: Capteur principal de temperature (en deg C) utilise pour la decision.
      selector:
        entity:
          domain: sensor
          device_class: temperature

    t1_helper:
      name: Temperature pour une protection moyenne
      description: >
        Seuil T1. Quand la temperature atteint T1 (avec hysteresis), la Scene 1 peut s appliquer.
      selector:
        entity:
          domain: input_number

    t2_helper:
      name: Temperature pour une protection intense (T2 > T1)
      description: >
        Seuil T2. Doit etre strictement superieur a T1. Quand la temperature atteint T2 (avec hysteresis),
        la Scene 2 peut s appliquer.
      selector:
        entity:
          domain: input_number

    t3_helper:
      name: Temperature de retour a l etat initial (T3 < T1)
      description: >
        Seuil T3. Doit etre strictement inferieur a T1. Si Temp < T3 pendant 10 min et que le
        garde T3 est arme, on ouvre les volets.
      selector:
        entity:
          domain: input_number

    scene_1:
      name: Scene a appliquer quand on atteint T1
      description: Scene appliquee pour la zone T1 (protection moyenne) avec hysteresis.
      selector:
        entity:
          domain: scene

    scene_2:
      name: Scene a appliquer quand on atteint T2
      description: Scene appliquee pour la zone T2 (protection intense) avec hysteresis.
      selector:
        entity:
          domain: scene

    covers:
      name: Volets a piloter (Pour retour a l etat initial et ouverture si T<T3)
      description: >
        Un ou plusieurs volets. Utilises pour le snapshot/restore avant coucher et pour l ouverture a T3.
      selector:
        entity:
          domain: cover
          multiple: true

    # --- Hysteresis (deg C) ---
    hys_t1:
      name: Hysteresis autour de T1 (deg C)
      description: Marge autour de T1 pour eviter les bascules rapides. Mettre 0 pour desactiver.
      default: 0.3
      selector:
        number:
          min: 0
          max: 5
          step: 0.1
          mode: slider
    hys_t2:
      name: Hysteresis autour de T2 (deg C)
      description: Marge autour de T2 pour eviter les bascules rapides. Mettre 0 pour desactiver.
      default: 0.3
      selector:
        number:
          min: 0
          max: 5
          step: 0.1
          mode: slider

    # --- Filtre Soleil (optionnel) ---
    sun_filter_enabled:
      name: Activer le filtre Soleil (Azimut/Elevation)
      description: >
        Si active, les scenes T1/T2 ne s appliquent que si le soleil est dans la fenetre azimut/elevation definie.
      default: false
      selector:
        boolean: {}
    azimuth_min:
      name: Azimut min (deg)
      description: Borne inferieure d azimut (0-360; 0=N, 90=E, 180=S, 270=O).
      default: 0
      selector:
        number:
          min: 0
          max: 360
          step: 1
          mode: slider
    azimuth_max:
      name: Azimut max (deg)
      description: >
        Borne superieure d azimut (0-360). Si min > max, la fenetre est circulaire (passe par 0).
      default: 360
      selector:
        number:
          min: 0
          max: 360
          step: 1
          mode: slider
    elevation_min:
      name: Elevation min (deg)
      description: Borne inferieure d elevation (angle au-dessus de l horizon, env. -6 a 90).
      default: -6
      selector:
        number:
          min: -90
          max: 90
          step: 1
          mode: slider
    elevation_max:
      name: Elevation max (deg)
      description: Borne superieure d elevation (angle au-dessus de l horizon).
      default: 90
      selector:
        number:
          min: -90
          max: 90
          step: 1
          mode: slider

    # --- Garde-fou T3 (obligatoire) ---
    t3_guard_helper:
      name: Drapeau T3 arme (input_boolean)
      description: Passe a ON quand Scene 1 ou Scene 2 s applique. T3 (ouverture) ne s execute que si ce drapeau est ON.
      selector:
        entity:
          domain: input_boolean

    # --- Etat de zone (obligatoire) ---
    zone_state_helper:
      name: Etat de zone T1/T2 (input_select)
      description: >
        Input_select avec options EXACTES : none, t1, t2. Sert a n executer T1/T2 qu une seule fois a l entree de zone.
      selector:
        entity:
          domain: input_select

    # --- Actions supplementaires (optionnelles) ---
    on_t1_actions:
      name: Actions supplementaires a T1 (apres Scene 1)
      description: Liste d actions a executer apres l application de Scene 1 (facultatif).
      default: []
      selector:
        action: {}
    on_t2_actions:
      name: Actions supplementaires a T2 (apres Scene 2)
      description: Liste d actions a executer apres l application de Scene 2 (facultatif).
      default: []
      selector:
        action: {}
    on_t3_actions:
      name: Actions supplementaires a T3 (apres ouverture volets)
      description: Liste d actions a executer apres l ouverture des volets quand Temp < T3 pendant 10 min (facultatif).
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

variables:
  v_temp_sensor: !input temp_sensor
  v_t1: !input t1_helper
  v_t2: !input t2_helper
  v_t3: !input t3_helper
  v_scene_1: !input scene_1
  v_scene_2: !input scene_2
  v_covers: !input covers

  v_h1: !input hys_t1
  v_h2: !input hys_t2

  v_sun_filter_enabled: !input sun_filter_enabled
  v_az_min: !input azimuth_min
  v_az_max: !input azimuth_max
  v_el_min: !input elevation_min
  v_el_max: !input elevation_max

  v_t3_guard: !input t3_guard_helper
  v_zone_state: !input zone_state_helper

  T: "{{ states(v_temp_sensor) | float(9999) }}"
  T1: "{{ states(v_t1) | float(9999) }}"
  T2: "{{ states(v_t2) | float(9999) }}"
  T3: "{{ states(v_t3) | float(-9999) }}"
  H1: "{{ v_h1 | float(0) }}"
  H2: "{{ v_h2 | float(0) }}"

  # Soleil
  SUN_AZ: "{{ state_attr('sun.sun', 'azimuth') | float(0) }}"
  SUN_EL: "{{ state_attr('sun.sun', 'elevation') | float(-90) }}"
  SUN_AZ_OK: >-
    {% set amin = v_az_min | float(0) %}
    {% set amax = v_az_max | float(360) %}
    {% set a = SUN_AZ %}
    {% if amin <= amax %}
      {{ a >= amin and a <= amax }}
    {% else %}
      {{ a >= amin or a <= amax }}
    {% endif %}
  SUN_EL_OK: "{{ SUN_EL >= (v_el_min|float(-90)) and SUN_EL <= (v_el_max|float(90)) }}"
  SUN_FILTER_PASSED: "{{ (not v_sun_filter_enabled) or (SUN_AZ_OK and SUN_EL_OK) }}"

  # Hysteresis
  APPLY_SCENE2: "{{ (T >= (T2 + H2)) and (T2 > T1) }}"
  APPLY_SCENE1: "{{ (T >= (T1 + H1)) and (T < (T2 - H2)) and (T2 > T1) and ((T2 - H2) > (T1 + H1)) }}"

  # Snapshot
  SNAP_ID: "{{ (this.entity_id | replace('.', '_')) ~ '_snapshot' }}"
  SNAP_ENTITY: "{{ 'scene.' ~ SNAP_ID }}"
  SNAP_EXISTS: "{{ not states(SNAP_ENTITY) in ['unknown','unavailable',''] }}"

  # Gardes
  T3_GUARD_OK: "{{ is_state(v_t3_guard, 'on') }}"
  ZONE_CUR: >-
    {% set z = states(v_zone_state) %}
    {{ 'none' if z in ['unknown','unavailable',''] else z }}

trigger_variables:
  t_sensor: !input temp_sensor
  t_t3: !input t3_helper

trigger:
  - id: evaluate
    platform: state
    entity_id:
      - !input temp_sensor
      - !input t1_helper
      - !input t2_helper
      - !input zone_state_helper

  - id: cooldown
    platform: template
    value_template: "{{ states(t_sensor)|float(9999) < states(t_t3)|float(9999) }}"
    for: "00:10:00"

  - id: sun_change
    platform: state
    entity_id: sun.sun

  - id: pre_sunset_restore
    platform: sun
    event: sunset
    offset: "-00:05:00"

condition: []

action:
  - choose:
      # 1) Restore avant coucher (si pas deja < T3) + desarmer garde + zone = none
      - conditions: "{{ trigger.id == 'pre_sunset_restore' and (T >= T3) }}"
        sequence:
          - if: "{{ SNAP_EXISTS }}"
            then:
              - service: scene.turn_on
                target:
                  entity_id: "{{ SNAP_ENTITY }}"
          - service: input_boolean.turn_off
            target:
              entity_id: !input t3_guard_helper
          - service: input_select.select_option
            target:
              entity_id: !input zone_state_helper
            data:
              option: "none"

      # 2) T < T3 pendant 10 min -> ouvrir volets SEULEMENT si garde arme -> OFF garde -> zone = none
      - conditions: "{{ trigger.id == 'cooldown' }}"
        sequence:
          - condition: template
            value_template: "{{ T3_GUARD_OK }}"
          - service: cover.open_cover
            target:
              entity_id: !input covers
          - alias: Actions supplementaires T3
            sequence: !input on_t3_actions
          - service: input_boolean.turn_off
            target:
              entity_id: !input t3_guard_helper
          - service: input_select.select_option
            target:
              entity_id: !input zone_state_helper
            data:
              option: "none"

      # 3) Evaluation (hysteresis + filtre Soleil) -> scenes + armer garde + actions T1/T2
      - conditions: "{{ (trigger.id == 'evaluate') or (trigger.id == 'sun_change' and v_sun_filter_enabled) }}"
        sequence:
          - condition: template
            value_template: "{{ SUN_FILTER_PASSED }}"

          # Snapshot juste avant la 1ere scene
          - if: "{{ not SNAP_EXISTS and (T >= (T1 + H1)) }}"
            then:
              - service: scene.create
                data:
                  scene_id: "{{ SNAP_ID }}"
                  snapshot_entities: !input covers

          # Entree en T2 -> unique
          - choose:
              - conditions: "{{ APPLY_SCENE2 and ZONE_CUR != 't2' }}"
                sequence:
                  - service: scene.turn_on
                    target:
                      entity_id: !input scene_2
                  - service: input_boolean.turn_on
                    target:
                      entity_id: !input t3_guard_helper
                  - alias: Actions supplementaires T2
                    sequence: !input on_t2_actions
                  - service: input_select.select_option
                    target:
                      entity_id: !input zone_state_helper
                    data:
                      option: "t2"

              # Entree en T1 -> unique
              - conditions: "{{ APPLY_SCENE1 and ZONE_CUR != 't1' }}"
                sequence:
                  - service: scene.turn_on
                    target:
                      entity_id: !input scene_1
                  - service: input_boolean.turn_on
                    target:
                      entity_id: !input t3_guard_helper
                  - alias: Actions supplementaires T1
                    sequence: !input on_t1_actions
                  - service: input_select.select_option
                    target:
                      entity_id: !input zone_state_helper
                    data:
                      option: "t1"
            default: []
    default: []
