blueprint:
  name: Volets - Scenes par paliers de temperature + filtre Soleil + retour avant coucher (+ actions T1/T2/T3)
  description: >
    Applique une scene selon T1/T2 (avec filtre Soleil optionnel). Si la temperature
    reste sous T3 pendant >=10 min, ouvre les volets. 5 min avant le coucher du soleil,
    restaure l etat initial. Permet d ajouter des actions libres a T1, T2 et T3.
  domain: automation
  input:
    temp_sensor:
      name: Capteur de temperature
      selector:
        entity:
          domain: sensor
          device_class: temperature
    t1_helper:
      name: Seuil T1 (input_number)
      selector:
        entity:
          domain: input_number
    t2_helper:
      name: Seuil T2 (input_number, > T1)
      selector:
        entity:
          domain: input_number
    t3_helper:
      name: Seuil T3 (input_number)
      selector:
        entity:
          domain: input_number
    scene_1:
      name: Scene 1 (T1 <= Temp < T2)
      selector:
        entity:
          domain: scene
    scene_2:
      name: Scene 2 (Temp >= T2)
      selector:
        entity:
          domain: scene
    covers:
      name: Volets a piloter
      selector:
        entity:
          domain: cover
          multiple: true

    # --- Filtre Soleil (optionnel) ---
    sun_filter_enabled:
      name: Activer le filtre Soleil (Azimut/Elevation)
      default: false
      selector:
        boolean: {}
    azimuth_min:
      name: Azimut min (deg)
      description: 0-360, 0=N, 90=E, 180=S, 270=O
      default: 0
      selector:
        number:
          min: 0
          max: 360
          step: 1
          mode: slider
    azimuth_max:
      name: Azimut max (deg)
      description: 0-360 (si min > max, l intervalle est considere circulaire)
      default: 360
      selector:
        number:
          min: 0
          max: 360
          step: 1
          mode: slider
    elevation_min:
      name: Elevation min (deg)
      description: Angle au-dessus de l horizon (-6 a 90)
      default: -6
      selector:
        number:
          min: -90
          max: 90
          step: 1
          mode: slider
    elevation_max:
      name: Elevation max (deg)
      default: 90
      selector:
        number:
          min: -90
          max: 90
          step: 1
          mode: slider

    # --- Actions supplementaires (optionnelles) ---
    on_t1_actions:
      name: Actions supplementaires a T1 (apres Scene 1)
      description: Liste d actions a executer apres l application de Scene 1.
      default: []
      selector:
        action: {}
    on_t2_actions:
      name: Actions supplementaires a T2 (apres Scene 2)
      description: Liste d actions a executer apres l application de Scene 2.
      default: []
      selector:
        action: {}
    on_t3_actions:
      name: Actions supplementaires a T3 (apres ouverture volets)
      description: Liste d actions a executer apres l ouverture des volets quand Temp < T3 pendant 10 min.
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

variables:
  v_temp_sensor: !input temp_sensor
  v_t1: !input t1_helper
  v_t2: !input t2_helper
  v_t3: !input t3_helper
  v_scene_1: !input scene_1
  v_scene_2: !input scene_2
  v_covers: !input covers

  v_sun_filter_enabled: !input sun_filter_enabled
  v_az_min: !i
