blueprint:
  name: Dynamic Heating Scheduler
  description: >
    Heating automation with dynamic YAML schedule slots, presence-aware presets,
    global heating enable, Versatile Thermostat window-state awareness,
    mobile push notifications and debug persistent notifications.
  domain: automation

  input:

    climate_list:
      name: Climate entities
      description: Optional explicit list of Versatile Thermostat climate devices
      selector:
        entity:
          domain: climate
          multiple: true

    area:
      name: Area
      description: All climate entities inside this area (alternative to climate_list)
      default: ""
      selector:
        area: {}

    heating_enabled:
      name: Global heating enable switch
      selector:
        entity:
          domain: input_boolean

    presence_sensor:
      name: Presence sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: occupancy

    workday_sensor:
      name: Workday sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: workday

    ###########################################################
    # YAML slot lists (the HA-compatible way for dynamic slots)
    ###########################################################
    workday_slots_yaml:
      name: Workday slots (YAML list)
      description: >
        YAML list of schedule slots.
        Example:
          - start: "06:30"
            preset_present: comfort
            preset_absent: eco_away
          - start: "09:00"
            preset_present: eco
            preset_absent: off
      selector:
        text:
          multiline: true

    non_workday_slots_yaml:
      name: Non-workday slots (YAML list)
      description: >
        YAML list of schedule slots.
        Example:
          - start: "08:30"
            preset_present: comfort
            preset_absent: eco_away
      selector:
        text:
          multiline: true

    push_notifications:
      name: Mobile notifications
      default: true
      selector:
        boolean: {}

    debug:
      name: Debug mode
      description: Enable persistent debug notifications
      default: false
      selector:
        entity:
          domain: input_boolean

mode: restart
max_exceeded: silent

trigger:
  - platform: time_pattern
    minutes: "/1"

  - platform: state
    entity_id: !input workday_sensor

  - platform: state
    entity_id: !input presence_sensor

variables:

  heating_enabled: !input heating_enabled
  presence: "{{ is_state((!input presence_sensor), 'on') }}"
  workday: "{{ is_state((!input workday_sensor), 'on') }}"

  debug_entity: !input debug
  debug_enabled: "{{ is_state((!input debug), 'on') }}"

  push_enabled: "{{ !input push_notifications }}"
  notify_service: "notify.mobile_app_iphone_de_thomas"

  climate_list: !input climate_list
  area: !input area

  ##########################################
  # Resolve climates
  ##########################################
  climates: >-
    {% if climate_list | length > 0 %}
      {{ climate_list }}
    {% else %}
      {{ expand(area_entities(area, 'climate')) | map(attribute='entity_id') | list }}
    {% endif %}

  ##########################################
  # Parse YAML slot lists
  ##########################################
  workday_slots: >
    {{ workday_slots_yaml | default("[]") | from_yaml }}

  non_workday_slots: >
    {{ non_workday_slots_yaml | default("[]") | from_yaml }}

  ##########################################
  # Choose slots based on workday
  ##########################################
  selected_slots: "{{ workday_slots if workday else non_workday_slots }}"
  now_time: "{{ now().strftime('%H:%M') }}"

  ##########################################
  # Determine active slot
  ##########################################
  active_slot: >-
    {% set t = now_time %}
    {% set lst = selected_slots | selectattr('start','<=',t) | list %}
    {% if lst | length == 0 %}
      {{ None }}
    {% else %}
      {{ lst[-1] }}
    {% endif %}

  ##########################################
  # VTherm window-state detection
  ##########################################
  vt_window_open: >-
    {{
      expand(climates)
      | selectattr('attributes.window_state','equalto','on')
      | list
      | length > 0
    }}

action:

  ############################################################
  # Global heating disabled -> force all off
  ############################################################
  - choose:
      - conditions:
          - condition: state
            entity_id: !input heating_enabled
            state: "off"
        sequence:
          - repeat:
              for_each: "{{ climates }}"
              sequence:
                - service: climate.turn_off
                  target:
                    entity_id: "{{ repeat.item }}"

          - if:
              - condition: template
                value_template: "{{ push_enabled }}"
            then:
              - service: "{{ notify_service }}"
                data:
                  title: "Heating disabled"
                  message: "Heating off because global switch is OFF."

          - if:
              - condition: template
                value_template: "{{ debug_enabled }}"
            then:
              - service: persistent_notification.create
                data:
                  title: "Heating debug"
                  message: "Global switch off. Heating stopped."
    default: []

  ############################################################
  # VTherm window detection -> block heating
  ############################################################
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ vt_window_open }}"
        sequence:

          - if:
              - condition: template
                value_template: "{{ push_enabled }}"
            then:
              - service: "{{ notify_service }}"
                data:
                  title: "Heating blocked"
                  message: "VTherm window_state detected as on. Heating blocked."

          - if:
              - condition: template
                value_template: "{{ debug_enabled }}"
            then:
              - service: persistent_notification.create
                data:
                  title: "Heating debug"
                  message: "VTherm window_state = on. Blocking all heating actions."
    default: []

  ############################################################
  # Determine desired preset
  ############################################################
  - variables:
      desired_preset: >-
        {% if active_slot is none %}
          off
        {% else %}
          {{ active_slot.preset_present if presence else active_slot.preset_absent }}
        {% endif %}

  ############################################################
  # Debug: context information
  ############################################################
  - if:
      - condition: template
        value_template: "{{ debug_enabled }}"
    then:
      - service: persistent_notification.create
        data:
          title: "Heating debug"
          message: >
            now = {{ now_time }}
            workday = {{ workday }}
            presence = {{ presence }}
            vt_window_open = {{ vt_window_open }}
            active_slot = {{ active_slot }}
            desired_preset = {{ desired_preset }}

  ############################################################
  # Apply preset or turn off
  ############################################################
  - choose:
      - conditions: "{{ desired_preset == 'off' }}"
        sequence:
          - repeat:
              for_each: "{{ climates }}"
              sequence:
                - service: climate.turn_off
                  target:
                    entity_id: "{{ repeat.item }}"

          - if:
              - condition: template
                value_template: "{{ push_enabled }}"
            then:
              - service: "{{ notify_service }}"
                data:
                  title: "Heating update"
                  message: "Heating turned off (preset = off)."

          - if:
              - condition: template
                value_template: "{{ debug_enabled }}"
            then:
              - service: persistent_notification.create
                data:
                  title: "Heating debug"
                  message: "Preset off applied."
    default:
      - repeat:
          for_each: "{{ climates }}"
          sequence:
            - service: climate.set_preset_mode
              target:
                entity_id: "{{ repeat.item }}"
              data:
                preset_mode: "{{ desired_preset }}"

      - if:
          - condition: template
            value_template: "{{ push_enabled }}"
        then:
          - service: "{{ notify_service }}"
            data:
              title: "Heating preset"
              message: "Applying preset '{{ desired_preset }}'."

      - if:
          - condition: template
            value_template: "{{ debug_enabled }}"
        then:
          - service: persistent_notification.create
            data:
              title: "Heating debug"
              message: "Preset '{{ desired_preset }}' applied."
