name: Blueprint Basic Validation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'blueprints/**/*.yml'
      - 'blueprints/**/*.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'blueprints/**/*.yml'
      - 'blueprints/**/*.yaml'

jobs:
  validate-yaml:
    name: Validate YAML Syntax
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install yamllint
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
      
      - name: Lint YAML files
        run: |
          yamllint blueprints/
  
  validate-blueprint-structure:
    name: Validate Blueprint Structure
    runs-on: ubuntu-latest
    needs: validate-yaml
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      
      - name: Make validation script executable
        run: chmod +x .github/scripts/validate_blueprint_schema.py
      
      - name: Validate blueprint schema
        run: python .github/scripts/validate_blueprint_schema.py
  
  check-documentation:
    name: Check Documentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      
      - name: Make documentation check executable
        run: chmod +x .github/scripts/check_docs_sync.py
      
      - name: Check documentation sync
        run: python .github/scripts/check_docs_sync.py
